### ISSUE TITLE
`JsonSerializationException` on `IssuesClient.GetIssuesAsync()`

### ISSUE THREAD

**Issue by NKnusperer** [autodesk-platform-services/aps-sdk-net#91]
Hello,
I'm receiving the described exception using the following code:

```csharp
var sdkManager = SdkManagerBuilder.Create().Build();
var issueClient = new IssuesClient(sdkManager);
var dataClient = new DataManagementClient(sdkManager);
var result = await issueClient.GetIssuesAsync(token, projectId, Region.US);
```

```text
Newtonsoft.Json.JsonSerializationException: Cannot convert null value to Autodesk.Construction.Issues.Model.AssignedToType. Path 'results[0].assignedToType', line 1, position 415.
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Autodesk.Construction.Issues.Client.LocalMarshalling.DeserializeAsync[T](HttpContent content)
   at Autodesk.Construction.Issues.Http.IssuesApi.GetIssuesAsync(String projectId, List`1 filterId, List`1 filterIssueTypeId, List`1 filterIssueSubtypeId, String filterStatus, List`1 filterLinkedDocumentUrn, Nullable`1 xAdsRegion, String filterDueDate, String filterStartDate, String filterCreatedAt, FiltercreatedBy filterCreatedBy, String filterUpdatedAt, List`1 filterUpdatedBy, List`1 filterAssignedTo, List`1 filterRootCauseId, List`1 filterLocationId, List`1 filterSubLocationId, List`1 filterClosedBy, String filterClosedAt, String filterSearch, Nullable`1 filterDisplayId, String filterAssignedToType, List`1 filterCustomAttributes, Nullable`1 filterValid, Nullable`1 limit, Nullable`1 offset, List`1 sortBy, List`1 fields, String accessToken, Boolean throwOnError)
   at Autodesk.Construction.Issues.IssuesClient.GetIssuesAsync(String accessToken, String projectId, Region xAdsRegion, List`1 filterId, List`1 filterIssueTypeId, List`1 filterIssueSubtypeId, String filterStatus, List`1 filterLinkedDocumentUrn, String filterDueDate, String filterStartDate, String filterCreatedAt, FiltercreatedBy filterCreatedBy, String filterUpdatedAt, List`1 filterUpdatedBy, List`1 filterAssignedTo, List`1 filterRootCauseId, List`1 filterLocationId, List`1 filterSubLocationId, List`1 filterClosedBy, String filterClosedAt, String filterSearch, Nullable`1 filterDisplayId, String filterAssignedToType, List`1 filterCustomAttributes, Nullable`1 filterValid, Nullable`1 limit, Nullable`1 offset, List`1 sortBy, List`1 fields, Boolean throwOnError)
```

**Comment by srivastavarahull** [comment]
Hi @NKnusperer,
This has been fixed in the latest release can please try using it.
https://www.nuget.org/packages/Autodesk.Construction.Issues/2.0.0-beta

**Comment by NKnusperer** [comment]
Fixed 👍
